### ISSUE TITLE
Formatting large files deletes all contents

### ISSUE THREAD

**Issue by indietyp** [koxudaxi/ruff-pycharm-plugin#224]
**Describe the bug**

I am currently creating a file full of models via `datamodel-code-generator` for [this specification](https://github.com/hashintel/hash/blob/main/apps/hash-graph/openapi/openapi.json).

When running ruff via the IDE plugin, it completely erases all contents.

**Expected behavior**

**Screenshots**
Also, gif movies are recommended.

https://github.com/koxudaxi/ruff-pycharm-plugin/assets/7252775/9a3586ac-9497-4156-a105-c24b66778dbd

Since taking this GIF, I have removed the black file watcher and still got the same result.

**Environments (please complete the following information):**
 - IDE: [e.g. PyCharm Community 2022.1 ] PyCharm Professional 2023.1.4
 - OS: [e.g. macOS  12.2.0 ] 13.4
 - Ruff Version [e.g. 1.9.0 ] ruff 0.0.278
 - Plugin version [e.g. 0.3.11 ] 0.0.18

**Additional context**

```
Unhandled exception in [CoroutineName(DocumentationBrowser requests), StandaloneCoroutine{Cancelling}@33e34d99, Dispatchers.Default]

The following command was executed:

<REDACTED>/.venv/bin/ruff --explain class

The exit code: 2
The error output of the command:


error: invalid value 'class' for '[RULE]': unknown rule code

For more information, try '--help'.

Error Running Ruff
	at com.koxudaxi.ruff.RuffKt.runCommand(Ruff.kt:191)
	at com.koxudaxi.ruff.RuffKt.runCommand(Ruff.kt:137)
	at com.koxudaxi.ruff.RuffKt.runRuff(Ruff.kt:242)
	at com.koxudaxi.ruff.RuffKt.runRuff(Ruff.kt:205)
	at com.koxudaxi.ruff.RuffNoqaDocumentationTarget$computeDocumentation$1.invokeSuspend(RuffNoqaDocumentationTarget.kt:34)
	at com.koxudaxi.ruff.RuffNoqaDocumentationTarget$computeDocumentation$1.invoke(RuffNoqaDocumentationTarget.kt)
	at com.koxudaxi.ruff.RuffNoqaDocumentationTarget$computeDocumentation$1.invoke(RuffNoqaDocumentationTarget.kt)
	at com.intellij.platform.backend.documentation.impl.ImplKt$computeDocumentation$2.invokeSuspend(impl.kt:34)
	at com.intellij.platform.backend.documentation.impl.ImplKt$computeDocumentation$2.invoke(impl.kt)
	at com.intellij.platform.backend.documentation.impl.ImplKt$computeDocumentation$2.invoke(impl.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:169)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.backend.documentation.impl.ImplKt.computeDocumentation(impl.kt:27)
	at com.intellij.lang.documentation.ide.impl.DocumentationPage.loadPage(DocumentationPage.kt:32)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser.handleBrowserRequest(DocumentationBrowser.kt:90)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser.access$handleBrowserRequest(DocumentationBrowser.kt:23)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser$1$1.invokeSuspend(DocumentationBrowser.kt:50)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser$1$1.invoke(DocumentationBrowser.kt)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser$1$1.invoke(DocumentationBrowser.kt)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invokeSuspend(Merge.kt:214)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Merge.kt)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Merge.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:34)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1.emit(Merge.kt:33)
	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:383)
	at kotlinx.coroutines.flow.SharedFlowImpl.collect(SharedFlow.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invokeSuspend(Merge.kt:27)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invoke(Merge.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invoke(Merge.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:264)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest.flowCollect(Merge.kt:25)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:157)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(ChannelFlow.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(DocumentationBrowser requests), StandaloneCoroutine{Cancelled}@33e34d99, Dispatchers.Default]
```

**Comment by indietyp** [comment]
right, this relates to: https://github.com/koxudaxi/datamodel-code-generator/issues/1433.

The config used is:

```
    poetry run datamodel-codegen \
      --input .hash/apps/hash-graph/openapi/openapi.bundle.json \
      --output hash_client/ffi/models.py \
      --output-model-type pydantic_v2.BaseModel \
      --input-file-type openapi \
      --use-standard-collections \
      --use-union-operator \
      --target-python-version 3.11 \
      --use-schema-description \
      --snake-case-field \
      --disable-timestamp \
      --enable-version-header \
      --enum-field-as-literal one \
      --use-double-quotes \
      --field-constraints \
      --allow-population-by-field-name
```

**Comment by koxudaxi** [comment]
@indietyp 
I tested your example with the latest Ruff plugin.
It works fine.
