### ISSUE TITLE
(🐞) Exception when 'pyproject.toml' file contains a syntax error

### ISSUE THREAD

**Issue by KotlinIsland** [koxudaxi/ruff-pycharm-plugin#239]
```
Caused by: The following command was executed:

C:\Users\AMONGUS\AppData\Local\pypoetry\Cache\virtualenvs\test-NzGwdVyt-py3.11\Scripts\ruff.exe --exit-zero --no-cache --force-exclude --no-fix --format json --stdin-filename AMONGUS.py -

The exit code: 2
The error output of the command:


ruff failed
  Cause: TOML parse error at line 58, column 1
   |
58 | <<<<<<< HEAD
   | ^
invalid key


Error Running Ruff
	at com.koxudaxi.ruff.RuffKt.runCommand(Ruff.kt:191)
	at com.koxudaxi.ruff.RuffKt.runCommand(Ruff.kt:137)
	at com.koxudaxi.ruff.RuffKt.runRuff(Ruff.kt:243)
	at com.koxudaxi.ruff.RuffExternalAnnotator.doAnnotate(RuffExternalAnnotator.kt:54)
	at com.koxudaxi.ruff.RuffExternalAnnotator.doAnnotate(RuffExternalAnnotator.kt:22)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:207)
	... 37 more
```

**Comment by koxudaxi** [comment]
Sorry for the late confirmation.
The latest version seems to have resolved the issue, so I will close it.

**Comment by KotlinIsland** [comment]
@koxudaxi, I am on 0.0.31, and I am still experiencing the issue
