### ISSUE TITLE
Cannot run program ruff-lsp - is not a valid Win32 application

### ISSUE THREAD

**Issue by michaelmaschinenf** [koxudaxi/ruff-pycharm-plugin#446]
**Describe the bug**
I don't get ruff linter hints in PyCharm 2024.1.1.

I'm running PyCharm 2024.1.1 + ruff-pycharm-plugin 0.0.33 on Windows 11 but my python project is inside WSL.
I've also installed `ruff` and `ruff-lsp` inside WSL. I can't get linter hints in my IDE. On the lower right of the IDE under "Language Services" I see "{} Ruff" with a red exclamation mark. It says "Ruff | Termianted". When I check the log it says **CreateProcess error=193, %1 is not a valid Win32 application**.

```
2024-05-22 11:49:09,031 [  18080] SEVERE - #c.i.d.PerformanceWatcherImpl - PyCharm 2024.1.1  Build #PY-241.15989.155
2024-05-22 11:49:09,031 [  18080] SEVERE - #c.i.d.PerformanceWatcherImpl - JDK: 17.0.10; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-05-22 11:49:09,031 [  18080] SEVERE - #c.i.d.PerformanceWatcherImpl - OS: Windows 11
2024-05-22 11:49:09,031 [  18080] SEVERE - #c.i.d.PerformanceWatcherImpl - Last Action: 
2024-05-22 11:49:09,103 [  18152]   INFO - #c.i.u.i.UnindexedFilesScanner - Scanning of fs2d-analytics uses 19 scanning threads
2024-05-22 11:49:09,244 [  18293]   INFO - #c.i.d.u.SqlDialects - SQL dialects initialized in 54 ms
2024-05-22 11:49:09,264 [  18313]   INFO - #c.i.w.i.i.EntitiesOrphanageImpl - Update orphanage. 0 modules added
2024-05-22 11:49:09,264 [  18313]   INFO - #c.i.w.i.i.WorkspaceModelImpl - Project model updated to version 3 in 0 ms: Sync global entities with project: fs2d-analytics
2024-05-22 11:49:09,264 [  18313]   INFO - #c.i.w.i.i.GlobalWorkspaceModel - Global model updated to version 2 in 0 ms: Sync global entities with state
2024-05-22 11:49:09,415 [  18464]   INFO - #c.i.p.l.i.LspServerImpl - RuffLspServerDescriptor@fs2d-analytics(Initializing;0): Starting LSP server
2024-05-22 11:49:09,425 [  18474]   INFO - #c.i.p.l.a.LspServerDescriptor - RuffLspServerDescriptor@fs2d-analytics: starting LSP server: \\wsl.localhost\Ubuntu-20.04\home\michael\.pyenv\shims\ruff-lsp []
2024-05-22 11:49:09,435 [  18484]   WARN - #c.i.p.l.i.LspServerImpl - RuffLspServerDescriptor@fs2d-analytics(Initializing;0): Failed to start LSP server
com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "\\wsl.localhost\Ubuntu-20.04\home\michael\.pyenv\shims\ruff-lsp": CreateProcess error=193, %1 is not a valid Win32 application
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:367)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:86)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:46)
	at com.intellij.platform.lsp.api.LspServerDescriptor$startServerProcess$1.<init>(LspServerDescriptor.kt:98)
	at com.intellij.platform.lsp.api.LspServerDescriptor.startServerProcess(LspServerDescriptor.kt:98)
	at com.intellij.platform.lsp.impl.connector.Lsp4jServerConnectorStdio.<init>(Lsp4jServerConnectorStdio.kt:17)
	at com.intellij.platform.lsp.impl.LspServerImpl.F(LspServerImpl.kt:318)
	at com.intellij.platform.lsp.impl.LspServerImpl.F(LspServerImpl.kt:298)
	at com.intellij.openapi.application.impl.RwLockHolder$executeOnPooledThread$1.run(RwLockHolder.kt:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.io.IOException: Cannot run program "\\wsl.localhost\Ubuntu-20.04\home\michael\.pyenv\shims\ruff-lsp": CreateProcess error=193, %1 is not a valid Win32 application
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:491)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:464)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:357)
	... 17 more
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:499)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:158)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 21 more
2024-05-22 11:49:09,435 [  18484]   INFO - #c.i.p.l.i.LspServerImpl - RuffLspServerDescriptor@fs2d-analytics(Initializing;0): Stopping LSP server unexpectedly
2024-05-22 11:49:09,445 [  18494]   INFO - #c.i.u.i.IndexingReasonExplanationLogger - Scanner has updated file workspace.xml with appliers: [SingleIndexValueApplier{indexId=filetypes, inputId=1279, fileInfo='workspace.xml(id=1279)'}] and removers: []; 
2024-05-22 11:49:09,507 [  18556]   INFO - #c.i.o.v.i.p.NewMappings - VCS Root: [Git] - [<Project>]
2024-05-22 11:49:09,517 [  18566]   INFO - #com.maddyhome.idea.vim.handler.EditorHandlersChainLogger - Esc handlers chain:
com.maddyhome.idea.vim.handler.VimEscLoggerHandler
```

**Expected behavior**
I want to get linter hints in my IDE.

**Screenshots**
<img width="1027" alt="ruff" src="https://github.com/koxudaxi/ruff-pycharm-plugin/assets/165894323/ab810707-6aa6-40c5-b5d0-93ccb8267225">

**Environments (please complete the following information):**
 - IDE: PyCharm 2024.1.1
 - OS: Windows 11 with WSL
 - Ruff Version 0.0.33
 - Plugin version [e.g. 0.3.11 ]

**Additional context**

**Comment by koxudaxi** [comment]
@michaelmaschinenf 
I'm sorry for the late action.
I have released the fixed version as 0.0.36
https://plugins.jetbrains.com/plugin/20574-ruff/versions/stable/597308
