### ISSUE TITLE
`--explain` is deprecated

### ISSUE THREAD

**Issue by InSyncWithFoo** [koxudaxi/ruff-pycharm-plugin#472]
An user-visible error is thrown when `# noqa: RUF001` or a similar `noqa` comment is hovered:

```text
error: `ruff --explain <RULE>` has been removed. Use `ruff rule <RULE>` instead.

Error Running Ruff
	at com.koxudaxi.ruff.RuffKt.runCommand(Ruff.kt:285)
	at com.koxudaxi.ruff.RuffKt.runCommand(Ruff.kt:214)
	at com.koxudaxi.ruff.RuffKt.runRuff(Ruff.kt:374)
	at com.koxudaxi.ruff.RuffKt.runRuff(Ruff.kt:324)
	at com.koxudaxi.ruff.RuffNoqaDocumentationTarget$computeDocumentation$1.invokeSuspend(RuffNoqaDocumentationTarget.kt:35)
	at com.koxudaxi.ruff.RuffNoqaDocumentationTarget$computeDocumentation$1.invoke(RuffNoqaDocumentationTarget.kt)
	at com.koxudaxi.ruff.RuffNoqaDocumentationTarget$computeDocumentation$1.invoke(RuffNoqaDocumentationTarget.kt)
```

The error is quite straightforward: The `--explain` option was removed, and its replacement is `rule`.

[This line](https://github.com/koxudaxi/ruff-pycharm-plugin/blob/df941b9dc473a093e0dcdb5b05c64b2fe950a50a/src/com/koxudaxi/ruff/RuffNoqaDocumentationTarget.kt#L35) is causing the problem:

```kotlin
val markdown = runRuff(psiComment.project, listOf("--explain", noqaCode), true)
```

It should be changed to:

```kotlin
val markdown = runRuff(psiComment.project, listOf("rule", noqaCode), true)
```

...though I guess it won't be that easy since support for old versions is probably desired.

**Comment by koxudaxi** [comment]
The  supported version was released 
[0.0.36](https://plugins.jetbrains.com/plugin/20574-ruff/versions/stable/597308)

Thank you
