### ISSUE TITLE
Warnings not displayed, pycharm reports plugin exception

### ISSUE THREAD

**Issue by anschweitzer** [koxudaxi/ruff-pycharm-plugin#478]
**Describe the bug**
Ruff inspections not displayed in code. Pycharm reports an internal error with: 

```
com.intellij.openapi.diagnostic.RuntimeExceptionWithAttachments: Read access is allowed from inside read-action only (see Application.runReadAction()); see https://jb.gg/ij-platform-threading for details
Current thread: Thread[#301,DefaultDispatcher-worker-7,5,main] 1711081316 (EventQueue.isDispatchThread()=false)
SystemEventQueueThread: Thread[#61,AWT-EventQueue-0,6,main] 1884486743
	at com.intellij.util.concurrency.ThreadingAssertions.createThreadAccessException(ThreadingAssertions.java:177)
	at com.intellij.util.concurrency.ThreadingAssertions.softAssertReadAccess(ThreadingAssertions.java:129)
	at com.intellij.openapi.editor.richcopy.HtmlSyntaxInfoUtil.appendHighlightedByLexerAndEncodedAsHtmlCodeSnippet(HtmlSyntaxInfoUtil.java:128)
	at com.intellij.lang.documentation.QuickDocHighlightingHelper.appendHighlightedCode(QuickDocHighlightingHelper.kt:295)
	at com.intellij.lang.documentation.QuickDocHighlightingHelper.appendStyledCodeBlock(QuickDocHighlightingHelper.kt:63)
	at com.intellij.lang.documentation.QuickDocHighlightingHelper.getStyledCodeBlock(QuickDocHighlightingHelper.kt:49)
	at com.intellij.markdown.utils.doc.impl.DocCodeBlockGeneratingProvider.processNode(DocGeneratingProviders.kt:62)
	at org.intellij.markdown.html.HtmlGenerator$HtmlGeneratingVisitor.visitNode(HtmlGenerator.kt:47)
	at org.intellij.markdown.ast.ASTNodeKt.accept(ASTNode.kt:15)
	at org.intellij.markdown.ast.ASTNodeKt.acceptChildren(ASTNode.kt:20)
	at org.intellij.markdown.html.HtmlGenerator$HtmlGeneratingVisitor.visitNode(HtmlGenerator.kt:48)
	at org.intellij.markdown.html.HtmlGenerator.generateHtml(HtmlGenerator.kt:41)
	at com.intellij.markdown.utils.doc.DocMarkdownToHtmlConverter.performConversion(DocMarkdownToHtmlConverter.kt:213)
	at com.intellij.markdown.utils.doc.DocMarkdownToHtmlConverter.convert(DocMarkdownToHtmlConverter.kt:140)
	at com.intellij.markdown.utils.doc.DocMarkdownToHtmlConverter.convert$default(DocMarkdownToHtmlConverter.kt:90)
	at com.intellij.markdown.utils.doc.DocMarkdownToHtmlConverter.convert(DocMarkdownToHtmlConverter.kt)
	at com.intellij.webSymbols.utils.HtmlMarkdownUtils.toHtml(HtmlMarkdownUtils.java:27)
	at com.koxudaxi.ruff.RuffNoqaDocumentationTarget$computeDocumentation$1.invokeSuspend(RuffNoqaDocumentationTarget.kt:36)
	at com.koxudaxi.ruff.RuffNoqaDocumentationTarget$computeDocumentation$1.invoke(RuffNoqaDocumentationTarget.kt)
	at com.koxudaxi.ruff.RuffNoqaDocumentationTarget$computeDocumentation$1.invoke(RuffNoqaDocumentationTarget.kt)
	at com.intellij.platform.backend.documentation.impl.ImplKt$computeDocumentation$2.invokeSuspend(impl.kt:35)
	at com.intellij.platform.backend.documentation.impl.ImplKt$computeDocumentation$2.invoke(impl.kt)
	at com.intellij.platform.backend.documentation.impl.ImplKt$computeDocumentation$2.invoke(impl.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.backend.documentation.impl.ImplKt.computeDocumentation(impl.kt:28)
	at com.intellij.lang.documentation.ide.impl.DocumentationPage.loadPage(DocumentationPage.kt:41)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser.handleBrowserRequest(DocumentationBrowser.kt:104)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser.access$handleBrowserRequest(DocumentationBrowser.kt:28)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser$1$1.invokeSuspend(DocumentationBrowser.kt:56)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser$1$1.invoke(DocumentationBrowser.kt)
	at com.intellij.lang.documentation.ide.impl.DocumentationBrowser$1$1.invoke(DocumentationBrowser.kt)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invokeSuspend(Merge.kt:213)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Merge.kt)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$mapLatest$1.invoke(Merge.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invokeSuspend(Merge.kt:30)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1$2.invoke(Merge.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:27)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:90)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:123)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:43)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3$1.emit(Merge.kt:29)
	at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:392)
	at kotlinx.coroutines.flow.SharedFlowImpl.collect(SharedFlow.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invokeSuspend(Merge.kt:23)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invoke(Merge.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest$flowCollect$3.invoke(Merge.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.CoroutineScopeKt.coroutineScope(CoroutineScope.kt:261)
	at kotlinx.coroutines.flow.internal.ChannelFlowTransformLatest.flowCollect(Merge.kt:21)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo$suspendImpl(ChannelFlow.kt:153)
	at kotlinx.coroutines.flow.internal.ChannelFlowOperator.collectTo(ChannelFlow.kt)
	at kotlinx.coroutines.flow.internal.ChannelFlow$collectToFun$1.invokeSuspend(ChannelFlow.kt:56)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
```

**To Reproduce**
Unclear. 
1. The plugin was working beautifully for a week. 
2. I upgraded pycharm from 2024.1 to 2024.2 and plugin from 0.0.34 to 0.0.35. 
3. The plugin continued to work beautifully for 1-2 days. 
4. I made changes to reduce ruff check warnings. 
5. The plugin stopped displaying warnings that ruff check finds and pycharm reported the crash above. 

I don't know why it seemed to reliably work well previously and why it reliably doesn't work well now. 

**Expected behavior**
Ruff warnings are shown highlighted in the code.

**Environments (please complete the following information):**
 - IDE: PyCharm 2024.2 (Professional Edition)
 - OS: macOS  14.4.1
 - Ruff Version: 0.5.7
 - Plugin version: 0.3.35

**Comment by anschweitzer** [comment]
Problem disappeared after upgrading to to ruff 0.6.1.
