### ISSUE TITLE
Run ruff in WSL

### ISSUE THREAD

**Issue by milhauzindahauz** [koxudaxi/ruff-pycharm-plugin#72]
**Describe the bug**
Triggering command from IDE results in exception

![image](https://user-images.githubusercontent.com/18167814/217528568-bebea15b-ee8a-4cf6-b63e-c620529276ac.png)

**Environments (please complete the following information):**
 - IDE: [PyCharm Professional Edition 2022.3.1]
 - OS: [Ubuntu 20.04 in WSL]
 - Ruff Version [0.0.243]
 - Plugin version [0.0.6]

**Comment by koxudaxi** [comment]
I am not familiar with WSL. But, I think we can't execute the ELF file from windows application 🤔 
Can we call ELF from a windows process via WSL?

**Comment by mastacheata** [comment]
You need to handle the path a bit, but then you can simply pass it to WSL.exe

i.e.: `\\wsl$\Ubuntu-20.04\home\benedikt\.local\bin\ruff check /home/benedikt/project` becomes `C:\Windows\system32\wsl.exe /home/benedikt/.local/bin/ruff check /home/benedikt/project`

So basically you strip the \\wsl$ and the distro name, then transpose the backslashes to forward slashes and pass it as an argument to wsl.exe (which is always located in C:\Windows\system32\wsl.exe)

The problem is you also need to translate the paths to the files you try to check in a similar way (i.e. drop wsl and the distro, translate backslashes to forward slashes)

In the File Watcher of PyCharm there are variables to help with translating those paths.
This is for example how I configured black (this is the arguments section, the actual tool to run is just WSL.exe):
`/home/benedikt/.local/bin/black /home/benedikt/develop/empto/$/FilePathRelativeToProjectRoot$`

**Comment by koxudaxi** [comment]
@mastacheata 
Thank you for being so helpful.
I will find the utils to convert the path in the PyCharm source code.
Also, I will check the internal API to treat WSL in PyCharm.

**Comment by rweintraub-cycleon** [comment]
any update on this? I was trying to use ruff in intellij today and i had the same error

**Comment by koxudaxi** [comment]
@rweintraub-cycleon 
I'm sorry I have not checked it yet :bow: 
I will check it this week.

**Comment by wholmen** [comment]
This would be very helpful for me as well. Will try to set it up following mastacheata's suggestion

**Comment by koxudaxi** [comment]
I just found a way to execute a command on WLS.
I will implement it.
https://github.com/JetBrains/intellij-community/blob/62f0f17610cb4f562a347ae90b5473f570c9360d/platform/platform-impl/src/com/intellij/execution/wsl/WslExecution.kt#L22-L25

**Comment by koxudaxi** [comment]
Hey @milhauzindahauz @mastacheata @rweintraub-cycleon @wholmen 
I have released the new version as `0.0.15`, which supports WSL
You can install it from the market.

**Comment by wholmen** [comment]
Hi @koxudaxi, I am trying to set it up now, but I don't manage to use a ruff config file. I have set it up like this, and I get the following Pycharm error:

![image](https://github.com/koxudaxi/ruff-pycharm-plugin/assets/5293373/59954803-0c06-43a4-9eb1-67649cf65baf)

I tried with both ruff.toml and pyproject.toml, but it seems the problem is related to concatenating paths 

<details><summary>Error message</summary>
<p>

ExternalToolPass: 

com.intellij.diagnostic.PluginException: annotator: com.koxudaxi.ruff.RuffExternalAnnotator@2ac91c72 (class com.koxudaxi.ruff.RuffExternalAnnotator) [Plugin: com.koxudaxi.ruff]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:89)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.processError(ExternalToolPass.java:259)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:207)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:198)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.runChangeAware(ExternalToolPass.java:274)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$1(ExternalToolPass.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:361)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:339)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:175)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:350)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:340)
	at com.intellij.util.ui.update.MergingUpdateQueue.doExecute(MergingUpdateQueue.java:297)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:280)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:245)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:249)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:365)
	at com.intellij.util.Alarm$Request.run(Alarm.java:354)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:248)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:28)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:221)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:227)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: The following command was executed:

\\wsl$\Ubuntu\home\wholmen\.cache\pypoetry\virtualenvs\xxx-V_HpjCWw-py3.11\bin\ruff --config \\wsl$\Ubuntu\home\wholmen\git\xxx\xxx\ruff.toml --exit-zero --no-cache --force-exclude --no-fix --format json --stdin-filename src/endpoints/api_version.py -

The exit code: 2
The error output of the command:

error: Failed to parse `/home/wholmen/git/xxx/xxx/\\wsl$\Ubuntu\home\wholmen\git\xxx\xxx\ruff.toml`: No such file or directory (os error 2)

Error Running Ruff
	at com.koxudaxi.ruff.RuffKt.runCommand(Ruff.kt:183)
	at com.koxudaxi.ruff.RuffKt.runCommand(Ruff.kt:133)
	at com.koxudaxi.ruff.RuffKt.runRuff(Ruff.kt:226)
	at com.koxudaxi.ruff.RuffExternalAnnotator.doAnnotate(RuffExternalAnnotator.kt:53)
	at com.koxudaxi.ruff.RuffExternalAnnotator.doAnnotate(RuffExternalAnnotator.kt:22)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:204)
	... 36 more

</p>
</details>
